[build]
  functions = "functions"  # path to your serverless functions folder
  publish = "public"       # path for any static files (e.g., if you have a frontend)

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
